const PDFDocument = require("pdfkit");

const generatePDF = (res, data) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  // ============================
  // Helpers
  // ============================

  const formatAmount = (amount) =>
    `GHS ${new Intl.NumberFormat("en-GH").format(amount)}`;

  const formatDate = (date) =>
    new Date(date).toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });

  const drawLine = () => {
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#d1d5db")
      .stroke();

    doc.moveDown();
  };

  const checkPage = () => {
    if (doc.y > 730) {
      doc.addPage();
    }
  };

  // ============================
  // Response Headers
  // ============================

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=Expense_Report_${
      new Date().toISOString().split("T")[0]
    }.pdf`
  );

  doc.pipe(res);

  // ============================
  // Header
  // ============================

  doc
    .font("Helvetica-Bold")
    .fillColor("#2563eb")
    .fontSize(24)
    .text("Expense Tracker Report", {
      align: "center",
    });

  doc.moveDown(0.5);

  doc
    .font("Helvetica")
    .fillColor("black")
    .fontSize(11)
    .text(`Generated: ${new Date().toLocaleDateString("en-GB")}`, {
      align: "center",
    });

  doc.moveDown(1.5);

  // ============================
  // Summary
  // ============================

  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor("#111827")
    .text("Summary");

  drawLine();

  doc.fontSize(13);

  doc.text(`Total Income: ${formatAmount(data.totalIncome)}`);
  doc.text(`Total Expenses: ${formatAmount(data.totalExpense)}`);
  doc.text(`Balance: ${formatAmount(data.balance)}`);

  doc.moveDown();

  // ============================
  // Income Section
  // ============================

  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor("#16a34a")
    .text("Income");

  drawLine();

  doc
    .fontSize(12)
    .fillColor("black")
    .font("Helvetica-Bold");

  doc.text("Date", 50);
  doc.text("Source", 180);
  doc.text("Amount", 430);

  doc.moveDown(0.5);

  doc.font("Helvetica");

  data.incomes.forEach((income) => {
    checkPage();

    const y = doc.y;

    doc.text(formatDate(income.date), 50, y);

    doc.text(income.source, 180, y, {
      width: 220,
    });

    doc.text(formatAmount(income.amount), 430, y);

    doc.moveDown();
  });

  doc.moveDown(2);

  // ============================
  // Expense Section
  // ============================

  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor("#dc2626")
    .text("Expenses");

  drawLine();

  doc
    .fontSize(12)
    .fillColor("black")
    .font("Helvetica-Bold");

  doc.text("Date", 50);
  doc.text("Category", 180);
  doc.text("Amount", 430);

  doc.moveDown(0.5);

  doc.font("Helvetica");

  data.expenses.forEach((expense) => {
    checkPage();

    const y = doc.y;

    doc.text(formatDate(expense.date), 50, y);

    doc.text(expense.category, 180, y, {
      width: 220,
    });

    doc.text(formatAmount(expense.amount), 430, y);

    doc.moveDown();
  });

  // ============================
  // Footer
  // ============================

  doc.moveDown(2);

  drawLine();

  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by Expense Tracker", {
      align: "center",
    });

  doc.end();
};

module.exports = generatePDF;